const constantParams = {
    port: 3000,
    mySqlDbConnectionUri : "localhost",
    user: "u804822716_rickyriccs",
    password: "IGhn#Rt]0",
    emailMsg: 'Email or password is missing',
    missingMsg: 'some data is missing',
    otpMsg: 'otp is missing',
    postMsg: 'post uploaded successfully',
    thumMsg: 'thumnail image should be on the second number',
    fileMsg: 'File should be two in numbers',
    authEmail: 'testshivramkashyap512@gmail.com',
    password: 'Sonalidubey@512',
    subject: 'otp verification code',
    otpSent: 'otp sent to your registered email address...',
    errMsg: 'something went wrong',
    authFail: 'authentication failed ... !',
    checkOtp: 'Please check your email for otp verification',
    otpNotSent: 'otp not sent, something went wrong in email',
    dataNotSave: 'data not saved to db',
    existMsg: 'email already exists',
    mailNotSent: 'email not sent',
    notSave: 'details are not saved to db',
    requestMsg: 'request successfully raised',
    succesMsg: 'verification successfull ... !',
    mailNotExist: 'email does not exists',
    otpCheck: 'please check the otp',
    logOut: 'User logged out successfully',
    wrongEmail: 'Email is incorrect',
    userArr: [{userId: "kashyapshivram512@gmail.com", role: "superAdmin", password: "test1"},
    {userId: "ricky@gmail.com", role: "superAdmin", password: "test2"},
    {userId: "rohit@gmail.com", role: "admin", password: "test3"},
    {userId: "rahul@gmail.com", role: "employee", password: "test4"}]
}

module.exports = constantParams